services:

  backend:
    build: .
    container_name: lms_backend
    restart: always
    environment:
      SERVER_PORT: 8082

      SPRING_DATASOURCE_URL: jdbc:postgresql://database-2.cbis22o66mf8.ap-south-1.rds.amazonaws.com:5432/test_name
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Elderstone123

      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 5
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: 1
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 60000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 30000
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000

    ports:
      - "8082:8082"
